## Training and Test datasets

In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [2]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [3]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict = {X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    # Predict
    print("Prediction: ", sess.run(prediction, feed_dict = {X: x_test}))
    # Accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict = {X: x_test, Y: y_test}))

0 5.73203 [[ 0.72881663  0.71536207 -1.18015325]
 [-0.57753736 -0.12988332  1.60729778]
 [ 0.48373488 -0.51433605 -2.02127004]]
1 3.318 [[ 0.66219079  0.74796319 -1.14612854]
 [-0.81948912  0.03000021  1.68936598]
 [ 0.23214608 -0.33772916 -1.94628811]]
2 2.0218 [[ 0.64342022  0.74127686 -1.12067163]
 [-0.81161296 -0.00900121  1.72049117]
 [ 0.2086665  -0.35079569 -1.909742  ]]
3 1.97109 [[ 0.62353212  0.74008238 -1.09958899]
 [-0.80967712 -0.01636279  1.72591698]
 [ 0.17870612 -0.33665746 -1.89391983]]
4 1.94468 [[ 0.60733104  0.73664987 -1.07995546]
 [-0.7900784  -0.03363196  1.72358739]
 [ 0.16691469 -0.3340635  -1.88472235]]
5 1.92357 [[ 0.59031737  0.73510242 -1.06139433]
 [-0.77496767 -0.0404885   1.71533322]
 [ 0.150766   -0.32209399 -1.88054323]]
6 1.90359 [[ 0.57437915  0.73262858 -1.04298222]
 [-0.75527775 -0.05152002  1.70667481]
 [ 0.13977794 -0.31497926 -1.87666988]]
7 1.88408 [[ 0.55812663  0.7307179  -1.02481902]
 [-0.73775685 -0.05928205  1.69691598]
 [ 0.1269844  -0.30

109 0.909591 [[-0.59192961  0.433846    0.42210928]
 [ 0.15041149 -0.01771637  0.76718187]
 [-0.33551797 -0.29530677 -1.42104602]]
110 0.904989 [[-0.59968174  0.43125218  0.43245521]
 [ 0.15442674 -0.01431536  0.75976562]
 [-0.33693343 -0.29794323 -1.41699409]]
111 0.900446 [[-0.60738969  0.4286783   0.44273701]
 [ 0.15840098 -0.01092672  0.75240272]
 [-0.33831945 -0.30056703 -1.41298425]]
112 0.895962 [[-0.61505389  0.42612448  0.45295504]
 [ 0.16233462 -0.00755141  0.74509376]
 [-0.33967602 -0.30317739 -1.40901732]]
113 0.891536 [[-0.62267482  0.42359087  0.46310961]
 [ 0.16622789 -0.00419021  0.73783928]
 [-0.3410033  -0.30577338 -1.40509403]]
114 0.887169 [[ -6.30252957e-01   4.21077579e-01   4.73201036e-01]
 [  1.70081198e-01  -8.44072551e-04   7.30639815e-01]
 [ -3.42301250e-01  -3.08354259e-01  -1.40121520e+00]]
115 0.882859 [[-0.63778871  0.4185847   0.48322964]
 [ 0.17389481  0.00248623  0.7234959 ]
 [-0.34356996 -0.31091926 -1.39738142]]
116 0.878606 [[-0.64528251  0.41611236